version: '3.8'
services:
  client:
    build: ./client
    ports:
      - "5173:5173"
    depends_on:
      - server
    networks:
      - wabot_net

  server:
    build: ./server
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    #      - PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true
    networks:
      - wabot_net

networks:
  wabot_net:
    driver: bridge
